scrape_configs:
  - job_name: 'totp-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['totp:8080']
  - job_name: 'totp-postgres'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ["totp-postgres-prometheus-exporter:9187"]
